### ISSUE TITLE
Data Download Bug When Selecting All Data

### ISSUE THREAD

**Issue by nharris-HEC** [HerreraEnvironmental/23-08082-000-TC-WQ-Dashboard#19]
Data download on the last tab won’t let you download all the data selected. Just says error, couldn’t download. Might just be a bug. I like the interface and that you can select the different data sets.

**Comment by R-Lionheart** [comment]
The downloading works fine for me; I do get a warning message about object lengths, which is coming from code lines 934 - 936. It has to do specifically with selecting parameters, and I'm guessing that's because there is missing data and NAs within the selections. As far as I can tell there aren't any problems with the downloaded csv, I did a bunch of random selections of data/locations etc and everything seems to be working ok.

**Comment by R-Lionheart** [comment]
@clarkbar88 and @R-Lionheart both ran this issue on local and web-hosted Shiny app, and had no problem selecting all or any of the data. Issue will be closed.
